services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    networks:
      - airflow_net

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      postgres:
        condition: service_healthy
      spark-master:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
      AIRFLOW__CORE__FERNET_KEY: "aNnPcgbBccqPI5E_PVPRPSXUtqHfn9dGjxBLrPPLsBw="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "True"
      AIRFLOW__WEBSERVER__SECRET_KEY: "my-super-secret-key" 
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./init-airflow.sh:/opt/airflow/init-airflow.sh
      - ./data:/opt/airflow/data
    networks:
      - airflow_net
    command: >
      bash -c "
        bash /opt/airflow/init-airflow.sh &&
        airflow scheduler
      "
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      postgres:
        condition: service_healthy
      spark-master:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
      AIRFLOW__CORE__FERNET_KEY: "aNnPcgbBccqPI5E_PVPRPSXUtqHfn9dGjxBLrPPLsBw="
      AIRFLOW__WEBSERVER__SECRET_KEY: "my-super-secret-key" 
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "True"
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./init-airflow-webserver.sh:/opt/airflow/init-airflow-webserver.sh
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    networks:
      - airflow_net
    command: >
      bash -c "
        bash /opt/airflow/init-airflow-webserver.sh &&
       airflow webserver
      "


  spark-master:
    build:
      context: ./spark_docker
      dockerfile: Dockerfile
    environment:
    - SPARK_NO_DAEMONIZE=1
    command: ["/opt/spark/sbin/start-master.sh", "-h", "0.0.0.0", "-p", "7077", "--webui-port", "8080"]
    ports:
      - "7077:7077"   # Spark master port for workers and spark-submit
      - "8081:8080"   # Spark master Web UI
    networks:
      - airflow_net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  spark-worker:
    build:
      context: ./spark_docker
      dockerfile: Dockerfile
    environment:
    - SPARK_NO_DAEMONIZE=1
    - SPARK_WORKER_MEMORY=2G
    - SPARK_WORKER_CORES=1
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    networks:
      - airflow_net
    volumes:
      - ./dags:/opt/airflow/dags/scripts/spark
      - ./data:/opt/airflow/data

networks:
  airflow_net:
    driver: bridge
